// src/pages/ApiKeysPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import {
  createApiKey,
  deleteApiKey,
  extractInvokeError,
  listApiKeys,
  updateApiKey,
  type ApiKeyPublic,
} from "../api/tauri";

const items = ref<ApiKeyPublic[]>([]);
const error = ref("");
const createdRaw = ref("");
const form = reactive({ name: "", enabled: true });

async function refresh() {
  try {
    items.value = await listApiKeys();
    error.value = "";
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

async function create() {
  try {
    const created = await createApiKey({ name: form.name, enabled: form.enabled });
    createdRaw.value = created.raw_key;
    form.name = "";
    form.enabled = true;
    await refresh();
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

async function toggle(item: ApiKeyPublic) {
  try {
    await updateApiKey({ id: item.id, name: item.name, enabled: !item.enabled });
    await refresh();
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

async function remove(id: number) {
  if (!confirm("确认删除该 Key？")) return;
  try {
    await deleteApiKey(id);
    await refresh();
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

async function copyRaw() {
  if (!createdRaw.value) return;
  await navigator.clipboard.writeText(createdRaw.value);
}

onMounted(refresh);
</script>

<template>
  <div class="space-y-6">
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 class="mb-4 text-base font-semibold">创建客户端 API Key</h2>
      <div class="flex flex-wrap items-end gap-3">
        <label class="text-sm">
          <span class="mb-1 block text-slate-500">名称</span>
          <input v-model="form.name" class="rounded-lg border border-slate-300 px-3 py-2" />
        </label>
        <label class="flex items-center gap-2 text-sm">
          <input v-model="form.enabled" type="checkbox" />
          启用
        </label>
        <button type="button" class="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white" @click="create">
          创建
        </button>
      </div>
      <div v-if="createdRaw" class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">
        <div class="mb-1 font-medium text-amber-800">请立即复制明文 Key（仅展示一次）</div>
        <div class="flex flex-wrap items-center gap-2">
          <code class="break-all font-mono text-xs">{{ createdRaw }}</code>
          <button type="button" class="rounded bg-amber-200 px-2 py-1 text-xs" @click="copyRaw">复制</button>
        </div>
      </div>
      <p v-if="error" class="mt-3 text-sm text-rose-600">{{ error }}</p>
    </section>

    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 class="mb-4 text-base font-semibold">Key 列表</h2>
      <div v-if="items.length === 0" class="text-sm text-slate-500">暂无 Key</div>
      <table v-else class="min-w-full text-left text-sm">
        <thead class="border-b text-slate-500">
          <tr>
            <th class="px-2 py-2">名称</th>
            <th class="px-2 py-2">脱敏</th>
            <th class="px-2 py-2">状态</th>
            <th class="px-2 py-2">操作</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in items" :key="item.id" class="border-b border-slate-100">
            <td class="px-2 py-2">{{ item.name }}</td>
            <td class="px-2 py-2 font-mono text-xs">{{ item.masked }}</td>
            <td class="px-2 py-2">{{ item.enabled ? "启用" : "停用" }}</td>
            <td class="px-2 py-2 space-x-2">
              <button type="button" class="text-cyan-700 hover:underline" @click="toggle(item)">
                {{ item.enabled ? "停用" : "启用" }}
              </button>
              <button type="button" class="text-rose-600 hover:underline" @click="remove(item.id)">删除</button>
            </td>
          </tr>
        </tbody>
      </table>
    </section>
  </div>
</template>

// src/pages/ApiKeysPage.tsx
import { useCallback, useEffect, useState, type FormEvent } from "react";
import {
  createApiKey,
  deleteApiKey,
  listApiKeys,
  maskSecret,
  updateApiKey,
  type ApiKey,
} from "../api/apikey";
import { GatewayGate } from "../components/GatewayGate";

interface ApiKeysPageProps {
  running: boolean;
  authOk: boolean;
  authMessage: string;
}

export function ApiKeysPage({ running, authOk, authMessage }: ApiKeysPageProps) {
  const [keys, setKeys] = useState<ApiKey[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState("local-client");
  const [createdKey, setCreatedKey] = useState<string | null>(null);
  const [copyHint, setCopyHint] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!running || !authOk) {
      return;
    }
    setLoading(true);
    setError(null);
    try {
      setKeys(await listApiKeys());
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [running, authOk]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const onCreate = async (event: FormEvent) => {
    event.preventDefault();
    setSaving(true);
    setError(null);
    setCopyHint(null);
    try {
      const created = await createApiKey({ name, enabled: true });
      const plain = created?.api_key ?? "";
      if (!plain) {
        throw new Error("创建成功但未返回 api_key，请刷新列表或检查侧车版本。");
      }
      setCreatedKey(plain);
      setName("local-client");
      await refresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  };

  const onCopy = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value);
      setCopyHint("已复制到剪贴板");
    } catch {
      setCopyHint("复制失败，请手动选中复制");
    }
  };

  const onToggleEnabled = async (item: ApiKey) => {
    setError(null);
    try {
      await updateApiKey({ id: item.id, enabled: !item.enabled, name: item.name });
      await refresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold">API 密钥</h2>
        <p className="mt-1 text-sm text-slate-600">
          管理客户端网关 API Key（前缀 <code className="rounded bg-slate-100 px-1">sk-octopus-</code>
          ）。与设置页中的管理 JWT 不是同一套凭证。
        </p>
      </div>

      <GatewayGate running={running} authOk={authOk} authMessage={authMessage}>
        {createdKey ? (
          <section
            role="status"
            className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 shadow-sm"
          >
            <h3 className="text-lg font-semibold text-emerald-900">创建成功</h3>
            <p className="mt-2 text-sm text-emerald-800">
              完整 Key 仅在此展示一次，请立即复制并妥善保存。关闭后列表中仅显示脱敏值。
            </p>
            <div className="mt-4 flex flex-col gap-2 md:flex-row md:items-center">
              <code className="flex-1 break-all rounded-lg border border-emerald-200 bg-white px-3 py-2 font-mono text-sm text-slate-900">
                {createdKey}
              </code>
              <button
                type="button"
                className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-600"
                onClick={() => void onCopy(createdKey)}
              >
                复制
              </button>
              <button
                type="button"
                className="rounded-lg border border-emerald-300 px-4 py-2 text-sm text-emerald-900"
                onClick={() => {
                  setCreatedKey(null);
                  setCopyHint(null);
                }}
              >
                关闭
              </button>
            </div>
            {copyHint ? (
              <p className="mt-2 text-sm text-emerald-800">{copyHint}</p>
            ) : null}
          </section>
        ) : null}

        <form
          onSubmit={(event) => void onCreate(event)}
          className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
        >
          <h3 className="text-lg font-semibold">新建 API 密钥</h3>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <label className="block text-sm md:col-span-2">
              <span className="font-medium text-slate-700">名称</span>
              <input
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                placeholder="例如 local-client"
              />
            </label>
          </div>
          <button
            type="submit"
            disabled={saving}
            className="mt-4 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-500 disabled:opacity-50"
          >
            {saving ? "创建中…" : "创建密钥"}
          </button>
        </form>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <h3 className="text-lg font-semibold">密钥列表</h3>
            <button
              type="button"
              onClick={() => void refresh()}
              className="rounded-lg border border-slate-200 px-3 py-1.5 text-sm"
            >
              刷新
            </button>
          </div>

          {error ? (
            <p role="alert" className="mt-4 text-sm text-red-600">
              {error}
            </p>
          ) : null}
          {loading ? (
            <p className="mt-4 text-sm text-slate-500">加载中…</p>
          ) : keys.length === 0 ? (
            <p className="mt-4 text-sm text-slate-500">暂无密钥，请先创建。</p>
          ) : (
            <ul className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">
              {keys.map((item) => (
                <li
                  key={item.id}
                  className="flex flex-col gap-3 px-4 py-3 md:flex-row md:items-center md:justify-between"
                >
                  <div>
                    <p className="font-medium">
                      {item.name}{" "}
                      <span className="text-xs text-slate-500">#{item.id}</span>
                    </p>
                    <p className="mt-1 font-mono text-xs text-slate-500">
                      {maskSecret(item.api_key)}
                    </p>
                    <p className="mt-1 text-xs text-slate-500">
                      {item.enabled ? "启用" : "禁用"}
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button
                      type="button"
                      className="rounded-lg border border-slate-200 px-3 py-1.5 text-sm"
                      onClick={() => void onToggleEnabled(item)}
                    >
                      {item.enabled ? "禁用" : "启用"}
                    </button>
                    <button
                      type="button"
                      className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-sm text-red-700"
                      onClick={() =>
                        void deleteApiKey(item.id)
                          .then(refresh)
                          .catch((err: unknown) => {
                            setError(err instanceof Error ? err.message : String(err));
                          })
                      }
                    >
                      删除
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </section>
      </GatewayGate>
    </div>
  );
}
