// src/pages/GroupsPage.tsx
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { listChannels, type Channel } from "../api/channel";
import {
  createRoundRobinGroup,
  deleteGroup,
  groupModeLabel,
  listGroups,
  updateRoundRobinGroup,
  type Group,
  type GroupItem,
} from "../api/group";
import { GatewayGate } from "../components/GatewayGate";

interface GroupsPageProps {
  running: boolean;
}

interface EditDraft {
  name: string;
  channelId: number | "";
  modelName: string;
}

function primaryItem(group: Group): GroupItem | undefined {
  return group.items?.[0];
}

export function GroupsPage({ running }: GroupsPageProps) {
  const [groups, setGroups] = useState<Group[]>([]);
  const [channels, setChannels] = useState<Channel[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState("my-model");
  const [channelId, setChannelId] = useState<number | "">("");
  const [modelName, setModelName] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editDraft, setEditDraft] = useState<EditDraft | null>(null);
  const [editSaving, setEditSaving] = useState(false);

  const channelMap = useMemo(() => {
    const map = new Map<number, Channel>();
    for (const channel of channels) {
      map.set(channel.id, channel);
    }
    return map;
  }, [channels]);

  const channelLabel = (id: number): string => {
    const channel = channelMap.get(id);
    return channel ? `#${id} ${channel.name}` : `#${id}`;
  };

  const formatBindings = (group: Group): string => {
    const items = group.items ?? [];
    if (items.length === 0) {
      return "无绑定成员";
    }
    return items
      .map((item) => `${channelLabel(item.channel_id)} → ${item.model_name}`)
      .join("；");
  };

  const refresh = useCallback(async () => {
    if (!running) {
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const [groupList, channelList] = await Promise.all([
        listGroups(),
        listChannels(),
      ]);
      setGroups(groupList);
      setChannels(channelList);
      setChannelId((current) => {
        if (current !== "" || !channelList[0]) {
          return current;
        }
        setModelName(channelList[0].model || "");
        return channelList[0].id;
      });
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [running]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  const onCreate = async (event: FormEvent) => {
    event.preventDefault();
    if (channelId === "") {
      setError("请选择渠道");
      return;
    }
    setSaving(true);
    setError(null);
    try {
      await createRoundRobinGroup({
        name,
        channelId,
        modelName,
      });
      await refresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSaving(false);
    }
  };

  const startEdit = (group: Group) => {
    if (group.id == null) {
      return;
    }
    const item = primaryItem(group);
    setEditingId(group.id);
    setEditDraft({
      name: group.name,
      channelId: item?.channel_id ?? (channels[0]?.id ?? ""),
      modelName: item?.model_name ?? channels[0]?.model ?? "",
    });
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditDraft(null);
  };

  const onSaveEdit = async (group: Group) => {
    if (!editDraft || group.id == null) {
      return;
    }
    if (editDraft.channelId === "") {
      setError("请选择渠道");
      return;
    }
    setEditSaving(true);
    setError(null);
    try {
      await updateRoundRobinGroup({
        id: group.id,
        name: editDraft.name,
        channelId: editDraft.channelId,
        modelName: editDraft.modelName,
        primaryItem: primaryItem(group) ?? null,
      });
      cancelEdit();
      await refresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setEditSaving(false);
    }
  };

  const onDelete = async (group: Group) => {
    if (group.id == null) {
      return;
    }
    const ok = window.confirm(
      `确定删除分组「${group.name}」(#${group.id})？客户端将无法再用此 model 名。`,
    );
    if (!ok) {
      return;
    }
    setError(null);
    try {
      await deleteGroup(group.id);
      if (editingId === group.id) {
        cancelEdit();
      }
      await refresh();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold">分组</h2>
        <p className="mt-1 text-sm text-slate-600">
          客户端请求中的{" "}
          <code className="rounded bg-slate-100 px-1">model</code> 填{" "}
          <strong>分组名</strong>；成员里的{" "}
          <code className="rounded bg-slate-100 px-1">model_name</code>{" "}
          是上游真实模型。默认负载：轮询（Round Robin）。
        </p>
      </div>

      <GatewayGate running={running}>
        <form
          onSubmit={(event) => void onCreate(event)}
          className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"
        >
          <h3 className="text-lg font-semibold">新建分组</h3>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <label className="block text-sm">
              <span className="font-medium text-slate-700">分组名（model）</span>
              <input
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </label>
            <label className="block text-sm">
              <span className="font-medium text-slate-700">渠道</span>
              <select
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"
                value={channelId === "" ? "" : String(channelId)}
                onChange={(e) => {
                  const id = Number(e.target.value);
                  setChannelId(id);
                  const channel = channels.find((item) => item.id === id);
                  if (channel?.model) {
                    setModelName(channel.model);
                  }
                }}
                required
              >
                <option value="" disabled>
                  请选择
                </option>
                {channels.map((channel) => (
                  <option key={channel.id} value={channel.id}>
                    #{channel.id} {channel.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="block text-sm md:col-span-2">
              <span className="font-medium text-slate-700">上游 model_name</span>
              <input
                className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"
                value={modelName}
                onChange={(e) => setModelName(e.target.value)}
                required
              />
            </label>
          </div>
          <button
            type="submit"
            disabled={saving || channels.length === 0}
            className="mt-4 rounded-lg bg-cyan-600 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-500 disabled:opacity-50"
          >
            {saving ? "创建中…" : "创建分组"}
          </button>
          {channels.length === 0 ? (
            <p className="mt-2 text-sm text-amber-700">
              请先在「渠道」页创建至少一个渠道。
            </p>
          ) : null}
        </form>

        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-semibold">分组列表</h3>
            <button
              type="button"
              className="rounded-lg border border-slate-200 px-3 py-1.5 text-sm"
              onClick={() => void refresh()}
            >
              刷新
            </button>
          </div>
          {error ? (
            <p role="alert" className="mt-4 text-sm text-red-600">
              {error}
            </p>
          ) : null}
          {loading ? (
            <p className="mt-4 text-sm text-slate-500">加载中…</p>
          ) : groups.length === 0 ? (
            <p className="mt-4 text-sm text-slate-500">暂无分组。</p>
          ) : (
            <ul className="mt-4 divide-y divide-slate-100 rounded-xl border border-slate-200">
              {groups.map((group) => {
                const isEditing =
                  group.id != null && editingId === group.id && editDraft;
                return (
                  <li key={group.id ?? group.name} className="px-4 py-3">
                    <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">
                      <div className="min-w-0">
                        <p className="font-medium">
                          {group.name}{" "}
                          {group.id != null ? (
                            <span className="text-xs text-slate-500">#{group.id}</span>
                          ) : null}
                        </p>
                        <p className="mt-1 text-xs text-slate-500">
                          {groupModeLabel(group.mode)} · 成员{" "}
                          {group.items?.length ?? 0}
                        </p>
                        <p className="mt-1 break-all text-xs text-slate-600">
                          绑定：{formatBindings(group)}
                        </p>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {group.id != null ? (
                          <button
                            type="button"
                            className="rounded-lg border border-slate-200 px-3 py-1.5 text-sm"
                            onClick={() =>
                              isEditing ? cancelEdit() : startEdit(group)
                            }
                          >
                            {isEditing ? "收起" : "编辑"}
                          </button>
                        ) : null}
                        {group.id != null ? (
                          <button
                            type="button"
                            className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-sm text-red-700"
                            onClick={() => void onDelete(group)}
                          >
                            删除
                          </button>
                        ) : null}
                      </div>
                    </div>

                    {isEditing && editDraft ? (
                      <div className="mt-4 rounded-xl border border-cyan-100 bg-cyan-50/40 p-4">
                        <p className="text-sm font-semibold text-slate-800">编辑分组</p>
                        <div className="mt-3 grid gap-3 md:grid-cols-2">
                          <label className="block text-sm">
                            <span className="font-medium text-slate-700">
                              分组名（客户端 model）
                            </span>
                            <input
                              className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2"
                              value={editDraft.name}
                              onChange={(e) =>
                                setEditDraft({ ...editDraft, name: e.target.value })
                              }
                              required
                            />
                          </label>
                          <label className="block text-sm">
                            <span className="font-medium text-slate-700">绑定渠道</span>
                            <select
                              className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2"
                              value={
                                editDraft.channelId === ""
                                  ? ""
                                  : String(editDraft.channelId)
                              }
                              onChange={(e) => {
                                const id = Number(e.target.value);
                                const channel = channels.find((c) => c.id === id);
                                setEditDraft({
                                  ...editDraft,
                                  channelId: id,
                                  modelName: channel?.model || editDraft.modelName,
                                });
                              }}
                              required
                            >
                              <option value="" disabled>
                                请选择
                              </option>
                              {channels.map((channel) => (
                                <option key={channel.id} value={channel.id}>
                                  #{channel.id} {channel.name}
                                </option>
                              ))}
                            </select>
                          </label>
                          <label className="block text-sm md:col-span-2">
                            <span className="font-medium text-slate-700">
                              上游 model_name
                            </span>
                            <input
                              className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2"
                              value={editDraft.modelName}
                              onChange={(e) =>
                                setEditDraft({
                                  ...editDraft,
                                  modelName: e.target.value,
                                })
                              }
                              required
                            />
                          </label>
                        </div>
                        <div className="mt-3 flex flex-wrap gap-2">
                          <button
                            type="button"
                            disabled={editSaving || channels.length === 0}
                            className="rounded-lg bg-cyan-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-cyan-500 disabled:opacity-50"
                            onClick={() => void onSaveEdit(group)}
                          >
                            {editSaving ? "保存中…" : "保存"}
                          </button>
                          <button
                            type="button"
                            className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm"
                            onClick={cancelEdit}
                            disabled={editSaving}
                          >
                            取消
                          </button>
                        </div>
                      </div>
                    ) : null}
                  </li>
                );
              })}
            </ul>
          )}
        </section>
      </GatewayGate>
    </div>
  );
}

// src/pages/GroupsPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import {
  createGroup,
  deleteGroup,
  extractInvokeError,
  listGroups,
  listHealth,
  listProviders,
  updateGroup,
  type Group,
  type HealthSnapshot,
  type Provider,
} from "../api/tauri";

const groups = ref<Group[]>([]);
const providers = ref<Provider[]>([]);
const health = ref<HealthSnapshot[]>([]);
const error = ref("");
const editing = ref<Group | null>(null);

const form = reactive({
  name: "",
  auto_failover: true,
  items: [] as { provider_id: number; upstream_model: string }[],
});

const providerMap = computed(() => new Map(providers.value.map((p) => [p.id, p])));

function healthLabel(providerId: number) {
  const h = health.value.find((x) => x.provider_id === providerId);
  if (!h) return "健康";
  if (h.state === "open") return "熔断";
  if (h.state === "half_open") return "半开";
  if (h.state === "warning") return "警告";
  return "健康";
}

async function refresh() {
  try {
    [groups.value, providers.value, health.value] = await Promise.all([
      listGroups(),
      listProviders(),
      listHealth(),
    ]);
    error.value = "";
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

function resetForm() {
  editing.value = null;
  form.name = "";
  form.auto_failover = true;
  form.items = [];
}

function startEdit(g: Group) {
  editing.value = g;
  form.name = g.name;
  form.auto_failover = g.auto_failover;
  form.items = g.items.map((i) => ({
    provider_id: i.provider_id,
    upstream_model: i.upstream_model,
  }));
}

function addItem() {
  const first = providers.value[0];
  form.items.push({
    provider_id: first?.id ?? 0,
    upstream_model: "gpt-4o-mini",
  });
}

function moveItem(index: number, delta: number) {
  const next = index + delta;
  if (next < 0 || next >= form.items.length) return;
  const arr = form.items;
  const tmp = arr[index];
  arr[index] = arr[next];
  arr[next] = tmp;
}

function removeItem(index: number) {
  form.items.splice(index, 1);
}

async function save() {
  try {
    const payload = {
      name: form.name,
      auto_failover: form.auto_failover,
      items: form.items.filter((i) => i.provider_id > 0 && i.upstream_model.trim()),
    };
    if (editing.value) {
      await updateGroup({ id: editing.value.id, ...payload });
    } else {
      await createGroup(payload);
    }
    resetForm();
    await refresh();
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

async function remove(id: number) {
  if (!confirm("确认删除该分组？")) return;
  try {
    await deleteGroup(id);
    await refresh();
  } catch (e) {
    error.value = extractInvokeError(e);
  }
}

onMounted(refresh);
</script>

<template>
  <div class="space-y-6">
    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 class="mb-4 text-base font-semibold">{{ editing ? "编辑分组" : "新建分组" }}</h2>
      <p class="mb-3 text-sm text-slate-500">分组名 = 客户端 model；队列顺序即故障转移优先级。</p>
      <div class="grid gap-3 md:grid-cols-2">
        <label class="text-sm">
          <span class="mb-1 block text-slate-500">分组名（对外 model）</span>
          <input v-model="form.name" class="w-full rounded-lg border border-slate-300 px-3 py-2" />
        </label>
        <label class="flex items-center gap-2 self-end text-sm">
          <input v-model="form.auto_failover" type="checkbox" />
          开启自动故障转移
        </label>
      </div>

      <div class="mt-4 space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium">故障转移队列</h3>
          <button type="button" class="text-sm text-cyan-700 hover:underline" @click="addItem">添加条目</button>
        </div>
        <div
          v-for="(item, index) in form.items"
          :key="index"
          class="flex flex-wrap items-center gap-2 rounded-lg border border-slate-200 p-3"
        >
          <span class="w-8 text-xs text-slate-400">#{{ index + 1 }}</span>
          <select v-model.number="item.provider_id" class="rounded border border-slate-300 px-2 py-1 text-sm">
            <option :value="0">选择供应商</option>
            <option v-for="p in providers" :key="p.id" :value="p.id">{{ p.name }}</option>
          </select>
          <input
            v-model="item.upstream_model"
            placeholder="上游模型名"
            class="min-w-[160px] flex-1 rounded border border-slate-300 px-2 py-1 text-sm"
          />
          <button type="button" class="text-xs text-slate-600" @click="moveItem(index, -1)">上移</button>
          <button type="button" class="text-xs text-slate-600" @click="moveItem(index, 1)">下移</button>
          <button type="button" class="text-xs text-rose-600" @click="removeItem(index)">删除</button>
        </div>
      </div>

      <div class="mt-4 flex gap-2">
        <button type="button" class="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white" @click="save">
          保存
        </button>
        <button
          v-if="editing"
          type="button"
          class="rounded-lg border border-slate-300 px-4 py-2 text-sm"
          @click="resetForm"
        >
          取消
        </button>
      </div>
      <p v-if="error" class="mt-3 text-sm text-rose-600">{{ error }}</p>
    </section>

    <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <h2 class="mb-4 text-base font-semibold">分组列表</h2>
      <div v-if="groups.length === 0" class="text-sm text-slate-500">暂无分组</div>
      <div v-for="g in groups" :key="g.id" class="mb-4 rounded-lg border border-slate-100 p-4 last:mb-0">
        <div class="mb-2 flex flex-wrap items-center justify-between gap-2">
          <div>
            <span class="font-semibold">{{ g.name }}</span>
            <span class="ml-2 text-xs text-slate-500">
              {{ g.auto_failover ? "自动故障转移：开" : "自动故障转移：关" }}
            </span>
          </div>
          <div class="space-x-2 text-sm">
            <button type="button" class="text-cyan-700 hover:underline" @click="startEdit(g)">编辑</button>
            <button type="button" class="text-rose-600 hover:underline" @click="remove(g.id)">删除</button>
          </div>
        </div>
        <ol class="space-y-1 text-sm">
          <li v-for="(item, idx) in g.items" :key="item.id" class="flex gap-2 text-slate-700">
            <span class="text-slate-400">{{ idx + 1 }}.</span>
            <span>{{ providerMap.get(item.provider_id)?.name || item.provider_name || item.provider_id }}</span>
            <span class="font-mono text-xs text-slate-500">{{ item.upstream_model }}</span>
            <span class="text-xs text-slate-400">{{ healthLabel(item.provider_id) }}</span>
          </li>
        </ol>
      </div>
    </section>
  </div>
</template>
